# Generated by Django 5.1.1 on 2024-09-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_cloudnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudnotification',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
